version: "3.4"

services:
  traefik:
    image: traefik:1.2
    volumes:
      # mount the docker socket into the container, not required if you use a TCP socket
      # note it's read only
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

    networks:
      - public
      - frontend

  rest-api:
    image: djmittens/mjolnir:rest-api-${VERSION:-latest}
    depends_on:
      - db
      # - redis
    networks:
      - frontend
      - backend

  db:
    image: mysql:8
    networks:
      - backend
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root


networks:
  #containers with publically mapped ports
  public:
  #the frontend is for applications containers that are web facing.
  frontend:
  backend:

volumes:
  mysql:


