# this line should be at the top of the file
defaultEntryPoints = ["http"]
logLevel = "DEBUG"
[entryPoints]
    # http should be redirected to https
    [entryPoints.http]
    address = ":80"

[web]
# Web admin port
address = ":8080"

[docker]

# Docker server endpoint. Can be a tcp or a unix socket endpoint.
#
# Required
#
endpoint = "unix:///var/run/docker.sock"

# Default domain used.
# Can be overridden by setting the "traefik.domain" label on a services.
#
# Required
#
domain = "mjolnir.dev"

# Enable watch docker changes
#
watch = true

