version: "3.3"

services:
  traefik:
    volumes:
      - "./traefik/config.toml:/etc/traefik/traefik.toml:ro"
  rest-api:
    build: ./rest-api/target/docker/stage/
    ports:
      - 9990:9990

    deploy:
      labels:
          - "traefik.frontend.rule=Host:localhost"
  db:
    ports:
     - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer

    ports:
      - 8081:8080

volumes:
  mysql:

