version: "3"

services:

  nginx:
    image: nginx:v12
    build: ./nginx
    # volumes:
    #   - ./nginx/volumes/ssl:/etc/nginx/ssl
    ports:
      - "80:8080"
      - "443:443"
    depends_on:
      - rest-api
    networks:
      - www
    restart: always

  rest-api:
    build: ./rest-api/target/docker/stage/
    image: rest-api:0.1
    ports:
      # - 8080:8080
      - 9990:9990
    depends_on:
      - db
      # - redis
    networks:
      - www
      - data

  db:
    image: mysql:nick
    build: ./mysql

    restart: always
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  mysql:

