version: "3.4"

services:
  ports:
    - target: 80
      published: 80
      protocol: tcp
      mode: ingress # ingress makes it globally avialable over all swarm mode
    - target: 443
      published: 443
      protocol: tcp
      mode: ingress
      # webui for traefik
    - target: 8080
      published: 8080
      protocol: tcp
      mode: ingress
